"""generate treatments table

Revision ID: 0c40079260d9
Revises: a737906b61a5
Create Date: 2024-05-30 11:21:13.592321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c40079260d9'
down_revision = 'a737906b61a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('vet_name', sa.String(length=100), nullable=True),
    sa.Column('cattle_id', sa.Integer(), nullable=True),
    sa.Column('drug_used', sa.String(length=100), nullable=True),
    sa.Column('method_of_administration', sa.String(length=100), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.serial_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treatment')
    # ### end Alembic commands ###
