"""generate pest control table

Revision ID: 4222912a0dd3
Revises: 21b67f9badd3
Create Date: 2024-05-30 11:10:03.593256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4222912a0dd3'
down_revision = '21b67f9badd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pest_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('cattle_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('pest_type', sa.String(length=100), nullable=True),
    sa.Column('pesticide_used', sa.String(length=100), nullable=True),
    sa.Column('vet_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.serial_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pest_control')
    # ### end Alembic commands ###
