"""generate periodic table

Revision ID: 21b67f9badd3
Revises: 2f25951a890c
Create Date: 2024-05-30 11:06:27.987552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b67f9badd3'
down_revision = '2f25951a890c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periodic_treatment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('cattle_id', sa.Integer(), nullable=True),
    sa.Column('vet_name', sa.String(length=100), nullable=True),
    sa.Column('disease', sa.String(length=100), nullable=True),
    sa.Column('method_of_administration', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.serial_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('periodic_treatment')
    # ### end Alembic commands ###
