"""generate customer table

Revision ID: 4bc6aec8fc6d
Revises: 62c26af93f2c
Create Date: 2024-05-30 10:37:26.652824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc6aec8fc6d'
down_revision = '62c26af93f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=100), nullable=True),
    sa.Column('billing_address', sa.String(length=255), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('shipping_address', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
