"""Added photo_url to cattle, farmer and worker 

Revision ID: 52c743fe7f6e
Revises: 4b31927fcf45
Create Date: 2024-07-23 20:29:28.762153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c743fe7f6e'
down_revision = '4b31927fcf45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cattle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('photo')

    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    with op.batch_alter_table('cattle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
