"""Added columns given_to calfs, consumed by staff, spillage, spoiled

Revision ID: 66181da3c477
Revises: 74be80659aad
Create Date: 2024-07-25 21:33:32.055589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66181da3c477'
down_revision = '74be80659aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milk_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('given_to_calf', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('consumed_by_staff', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('spillage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('spoiled', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milk_sales', schema=None) as batch_op:
        batch_op.drop_column('spoiled')
        batch_op.drop_column('spillage')
        batch_op.drop_column('consumed_by_staff')
        batch_op.drop_column('given_to_calf')

    # ### end Alembic commands ###
