"""generate dehorning table

Revision ID: 79e2512c3dca
Revises: 4bc6aec8fc6d
Create Date: 2024-05-30 10:42:12.838895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79e2512c3dca'
down_revision = '4bc6aec8fc6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dehorning',
    sa.Column('dehorning_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('vet_name', sa.String(length=100), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('cattle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.serial_number'], ),
    sa.PrimaryKeyConstraint('dehorning_id'),
    sa.UniqueConstraint('cattle_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dehorning')
    # ### end Alembic commands ###
