"""Added columns given_to calfs, consumed by staff, spillage, spoiled on MilkProduction

Revision ID: 8b7c290e7a92
Revises: 66181da3c477
Create Date: 2024-07-25 21:40:05.706826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7c290e7a92'
down_revision = '66181da3c477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milk_production', schema=None) as batch_op:
        batch_op.add_column(sa.Column('given_to_calf', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('consumed_by_staff', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('spillage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('spoiled', sa.Float(), nullable=True))

    with op.batch_alter_table('milk_sales', schema=None) as batch_op:
        batch_op.drop_column('spillage')
        batch_op.drop_column('consumed_by_staff')
        batch_op.drop_column('spoiled')
        batch_op.drop_column('given_to_calf')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('milk_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('given_to_calf', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('spoiled', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('consumed_by_staff', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('spillage', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('milk_production', schema=None) as batch_op:
        batch_op.drop_column('spoiled')
        batch_op.drop_column('spillage')
        batch_op.drop_column('consumed_by_staff')
        batch_op.drop_column('given_to_calf')

    # ### end Alembic commands ###
