"""New column cost on procedures

Revision ID: b44f0aa7b750
Revises: 8b7c290e7a92
Create Date: 2024-07-29 13:27:34.941285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44f0aa7b750'
down_revision = '8b7c290e7a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artificial_insemination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    with op.batch_alter_table('calving', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    with op.batch_alter_table('dehorning', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    with op.batch_alter_table('deworming', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    with op.batch_alter_table('miscarriage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    with op.batch_alter_table('natural_insemination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    with op.batch_alter_table('pest_control', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    with op.batch_alter_table('pregnancy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    with op.batch_alter_table('vaccination', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccination', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('treatment', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('pregnancy', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('pest_control', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('natural_insemination', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('miscarriage', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('deworming', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('dehorning', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('calving', schema=None) as batch_op:
        batch_op.drop_column('cost')

    with op.batch_alter_table('artificial_insemination', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
